name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: make
        run: make

      - name: Install xvfb
        run: sudo apt-get install -y xvfb
  
      - name: Run Tests with xvfb
        run: xvfb-run env TERM=xterm ./gameoflife.exe --run-tests
